# Generated by Django 6.0 on 2026-01-09 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteOlympique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Typologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarquable', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type de reconnaissance patrimoniale')),
                ('departement', models.IntegerField(blank=True, null=True)),
                ('commune', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('informations_transport', models.TextField(blank=True, null=True, verbose_name="Informations d'accès en transport en commun")),
                ('appellation', models.CharField(max_length=255, verbose_name='Nom du site')),
                ('datation', models.CharField(blank=True, max_length=255, null=True)),
                ('periode_construction', models.CharField(blank=True, max_length=255, null=True, verbose_name='Période de construction')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Historique et description')),
                ('credits', models.CharField(blank=True, max_length=255, null=True)),
                ('url_image', models.URLField(blank=True, max_length=500, null=True)),
                ('dates_reference', models.ManyToManyField(blank=True, related_name='sites', to='patrimoine_sportif.datereference')),
                ('denominations', models.ManyToManyField(blank=True, related_name='sites', to='patrimoine_sportif.denomination')),
                ('site_olympique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='patrimoine_sportif.siteolympique')),
                ('typologies', models.ManyToManyField(blank=True, related_name='sites', to='patrimoine_sportif.typologie')),
            ],
        ),
    ]
